Pract2E13: vehiculos Namespace Reference
vehiculos Namespace Reference
Classes
struct Vehiculo
Functions
Vehiculo & operator= (const Vehiculo &v)
void LeePorTeclado (Vehiculo &p)
Prompts the user for a vehicle's data and stores it in the provided structure.
void rellenarVector (Vehiculo v[], int tamv)
fills a vector
void muestraEnPantalla (const Vehiculo &p)
shown on screen
void mostrarEnPantalla (const Vehiculo *v, int tamv)
shown on screen
int MaxPrecio (Vehiculo p[], int tamv)
shows the highest priced car
int buscarPorMatricula (string matricula, Vehiculo v[], int tamv)
void cargaEnTransporte (Vehiculo v[], int nVehiculos)
sum of weight
Function Documentation
buscarPorMatricula()
int vehiculos::buscarPorMatricula (string matricula, Vehiculo v[], int tamv)
Referenced by main().
cargaEnTransporte()
void vehiculos::cargaEnTransporte (Vehiculo v[], int nVehiculos)
sum of weight
Parameters
[in] v Reference to a Vehicle object where the entered data will be saved.
nVehicles number of vehicles we want to sum their wight
Postcondition
adds the weight of all the vehicles and if it exceeds 10,000kg it will throw an exception
Definition at line 142 of file vehiculo.cpp.
References vehiculos::Vehiculo::peso.
Referenced by main().
LeePorTeclado()
void vehiculos::LeePorTeclado (Vehiculo & p)
Prompts the user for a vehicle's data and stores it in the provided structure.
Parameters
[in] p Reference to a Vehicle object where the entered data will be saved.
Postcondition
The p object will contain the data entered by the user, as long as it is valid.
Exceptions
string If the flag is less than 3 or more than 20 characters.
string If the model is less than 1 or more than 30 characters.
string If the license plate does not have exactly 6 characters.
string If the price is negative.
Definition at line 22 of file vehiculo.cpp.
References vehiculos::Vehiculo::afabricacion, vehiculos::Vehiculo::marca, vehiculos::Vehiculo::matricula, vehiculos::Vehiculo::modelo, vehiculos::Vehiculo::peso, and vehiculos::Vehiculo::precio.
Referenced by main(), and rellenarVector().
MaxPrecio()
int vehiculos::MaxPrecio (Vehiculo p[], int tamv)
shows the highest priced car
Parameters
[in] p Reference to a Vehicle object where the entered data will be saved.
[in] tamv Size of the vector that we are going to fill
Postcondition
shows the highest priced car
Returns
pos , is the position where it is the car with the highest price
Definition at line 106 of file vehiculo.cpp.
Referenced by main().
mostrarEnPantalla()
void vehiculos::mostrarEnPantalla (const Vehiculo * v, int tamv)
shown on screen
Parameters
[in] v Reference to a Vehicle object where the entered data will be saved.
[in] tamv Size of the vector that we are going to fill
Postcondition
shows the cars on the screen 5 by 5
Definition at line 86 of file vehiculo.cpp.
References muestraEnPantalla().
Referenced by main().
muestraEnPantalla()
void vehiculos::muestraEnPantalla (const Vehiculo & p)
shown on screen
Parameters
[in] v Reference to a Vehicle object where the entered data will be saved.
Postcondition
shows all the cars entered on the screen
Definition at line 70 of file vehiculo.cpp.
References vehiculos::Vehiculo::afabricacion, vehiculos::Vehiculo::marca, vehiculos::Vehiculo::matricula, vehiculos::Vehiculo::modelo, and vehiculos::Vehiculo::precio.
Referenced by main(), and mostrarEnPantalla().
operator=()
Vehiculo& vehiculos::operator= (const Vehiculo & v)
Definition at line 34 of file vehiculo.h.
rellenarVector()
void vehiculos::rellenarVector (Vehiculo v[], int tamv)
fills a vector
Parameters
[in] v Reference to a Vehicle object where the entered data will be saved.
[in] tamv Size of the vector that we are going to fill
Postcondition
fills the vector by calling the ReadByKeyboard function
Definition at line 60 of file vehiculo.cpp.
References LeePorTeclado().
Referenced by main().